# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

# source /nix/store/9ms4j1mw7zwfx47a98dkp6fvr1nzi5sq-hm-session-vars.fish
source $HOME/.config/fish/zoxide.fish


status is-login; and begin

    # Login shell initialisation


end

status is-interactive; and begin

    # Abbreviations


    # Aliases
    alias gamemode-proton-run 'gamemoderun /home/mohammed/Drives/nvme1n1p5/SteamLibrary/steamapps/common/Proton - Experimental/proton run'
    alias ls 'eza --group-directories-first'
    alias update-channels 'sudo nix-channel --update && nix-channel --update'
    alias update-sys 'sudo nixos-rebuild switch --upgrade'
    alias reload-cfg 'sudo nixos-rebuild switch'
    alias vim hx
    alias cd z
    alias steam 'steam -forcedesktopscaling=1.5'
    # Interactive shell initialisation
    export EDITOR="hx"
    export STEAM_COMPAT_DATA_PATH="$HOME/.proton"
    export STEAM_COMPAT_CLIENT_INSTALL_PATH="$HOME/.steam/steam"
    set PATH $HOME/.cargo/bin $HOME/.local/bin $PATH

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/mohammed/.local/share/fish/home-manager_generated_completions" $post
    end


end
